version: '2.0'

services:

  zookeeper:
    build: ../kafka
    entrypoint: ./bin/zookeeper-server-start.sh
    command:
      - config/zookeeper.properties

  kafka-0:
    build: ../kafka
    links:
      - zookeeper
    environment:
      - JMX_PORT=5555
    expose:
      - '5555'
    entrypoint: ./bin/kafka-server-start.sh
    command:
      - config/server.properties
      - --override
      -   zookeeper.connect=zookeeper:2181
      - --override
      -   broker.id=0
      - --override
      -   advertised.listener=PLAINTEXT://kafka-0:9092

  prometheus-jmx-exporter:
    build: ../prometheus-jmx-exporter
    links:
      - kafka-0
    # patch a config before start, as the image is designed for use with local JMX (same k8s pod)
    entrypoint: /bin/bash
    command:
      - -c
      - >
        sed -i 's|127.0.0.1|kafka-0|' example_configs/kafka-prometheus-monitoring.yml;
        cat example_configs/kafka-prometheus-monitoring.yml;
        java -jar jmx_prometheus_httpserver.jar
        5556 example_configs/kafka-prometheus-monitoring.yml

  test-metrics-export:
    image: solsson/curl@sha256:92ebf15ac57bea360484480336ed5d9fa16d38d773fd00f7e9fb2cae94baf25a
    command:
      - --fail-early
      - --retry
      -   '10'
      - --retry-delay
      -   '3'
      - --retry-connrefused
      - http://prometheus-jmx-exporter:5556/metrics

  connect-jmx:
    build: ../connect-jmx
    links:
      - kafka-0

  test-jmx:
    image: solsson/kafkacat@sha256:7a5961f861ddad53c25227511b9f36a5c13bc43296470b383be2f3e8e3a506f4
    command:
      - -exc
      - sleep 10;
      - kafkacat
      - -b
      - kafka-0:9092
      - -t
      - jmx-test
      - -C
      - -o
      - beginning
