version: '2.0'

services:

  zookeeper:
    build: ../kafka
    entrypoint: ./bin/zookeeper-server-start.sh
    command:
      - config/zookeeper.properties

  kafka-0:
    build: ../kafka
    links:
      - zookeeper
    entrypoint: ./bin/kafka-server-start.sh
    command:
      - config/server.properties
      - --override
      -   zookeeper.connect=zookeeper:2181
      - --override
      -   broker.id=0
      - --override
      -   advertised.listener=PLAINTEXT://kafka-0:9092

  test-topic-create:
    build: ../kafka
    links:
      - kafka-0
    entrypoint: ./bin/kafka-topics.sh
    command:
      - --zookeeper
      -   zookeeper:2181
      - --create
      - --topic
      -   test-topic-create
      - --partitions
      -   '1'
      - --replication-factor
      -   '1'

  test-snappy-compression:
    image: solsson/kafkacat@sha256:7a5961f861ddad53c25227511b9f36a5c13bc43296470b383be2f3e8e3a506f4
    entrypoint: /bin/sh
    command:
      - -exc
      - sleep 5; echo "Message from $${HOSTNAME} at $$(date)" | kafkacat -z snappy -b kafka-0:9092 -t test1 -P

  test-consume-all:
    image: solsson/kafkacat@sha256:7a5961f861ddad53c25227511b9f36a5c13bc43296470b383be2f3e8e3a506f4
    entrypoint: /bin/sh
    command:
      - -exc
      - sleep 10;
      - kafkacat
      - -b
      - kafka-0:9092
      - -t
      - test1
      - -C
      - -o
      - beginning
      - -e
