FROM reddone/kafka@sha256:sha256:1d74f0a05694e68262082f6098ae093dc65f60a6d7d60e8a5d9659c675289557

ENV CP_ARCHIVE_VERSION=v5.0.0 \
    CP_PACKAGE_VERSION=5.0.0 \
    MAVEN_VERSION=3.5.2 \
    MAVEN_FLAGS="-Dmaven.test.skip=true"
# Default versions are found in the corresponding branch of: https://github.com/confluentinc/common/blob/master/pom.xml

WORKDIR /usr/local

